spring:
  application:
    name: sakuragi-gateway

server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

zuul:
  prefix: /sk   # 统一的前缀
  routes:       # 配置微服务的转发
    product:    # 起一个微服务的名字，这个名字可以是任意的
      path: /product/**  # product 模块中的context-path的值;?匹配单个字符,*匹配多个字符，**匹配多级目录
      serviceId: service-product   #微服务的名字,通过serviceId找到转发的微服务
      strip-prefix: false # 是否跳过前缀,false表示不跳过前缀
